### ISSUE TITLE
MIT License

### ISSUE THREAD

**Issue by mariecl** [yaronn/test-creep#2]
Hi,

Your `package.json` file mentions an MIT License for `test-creep`, but the README doesn't make any mention of it. Could you please confirm that the code is published under the MIT License?
I am working on a package that is derived from yours and I'll be unable to make it public if yours is not licensed, so it would be great to have you confirm that there is or there is no MIT license.

Thanks for your help with this issue.
Best,

  Marie.

**Comment by yaronn** [comment]
Hi @mariecl 

Yes, it is MIT. I have added it to the README. Would love to get a link once you publish your library!

Yaron

**Comment by mariecl** [comment]
Thanks a lot! I'll be sure to let you know when everything is ready.

**Comment by mariecl** [comment]
Hey!
This is the package I worked on that is derived from `test-creep`: [`quick-coverage`](https://www.npmjs.com/package/quick-coverage). The logic is very similar and I kept big chunks of the code, but the focus is on getting coverage reports only for files which were modified (and running all tests). I still need to add some tests but I am happy it's published and usable now!
Thanks again.

**Comment by yaronn** [comment]
thanks for sharing, looks super useful!
